name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone viewer
      uses: actions/checkout@v2
      with:
        repository: vasyaod/my-trips-viewer
        path: my-trips-code

    - name: Clone repo of pages
      uses: actions/checkout@v2
      with:
        repository: vasyaod/my-trips
        path: my-trips

    - name: Clone data
      uses: actions/checkout@v2
      with:
        path: my-trips-data

    - name: Compile site code
      run: |
        cd my-trips-code/viewer
        npm install
        npm run build
        cd ../..
        cp -u my-trips-code/viewer/bundle.js my-trips

    - name: Data processing
      env: 
        INPUT_DATA_PATH: ../../my-trips/initial-data
        OUTPUT_DATA_PATH: ../../my-trips
      run: |
        cd my-trips-code/etl
        npm install
        npm run lets-do-this

    - name: Run site in dev mode
      run: |
        ln -sf my-trips/data my-trips-code/viewer/data
        ln -sf my-trips/images my-trips-code/viewer/images
        ls my-trips-code/viewer
        cd my-trips-code/viewer
        npm install
        npm run dev &
        cd ../..

    - name: Make preview for every trip
      env: 
        INPUT_DATA_PATH: ../../my-trips/initial-data
        OUTPUT_DATA_PATH: ../../my-trips
      run: |
        cd my-trips-code/previewer
        npm install
        npm run lets-do-this
        cd ../..

    - name: Commit my-trips page
      run: |
        cd my-trips
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes" -a


    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: my-trips
        repository: vasyaod/my-trips
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run a multi-line script
      run: |
        echo Add other actions to build1,
        echo test, and deploy your project.
